### ISSUE TITLE
Support for other Node Platforms

### ISSUE THREAD

**Issue by casoetan** [ForestAdmin/forest-express-sequelize#23]
Hi @VinzGhyz 
Just got your mail and was quite interested in your project.

Any plans to support other node applications, particularly HapiJS, or you could setup a guide for extending this to other node platforms.

PS. How about Bookshelf.js and Knex.

Cheers

**Comment by VinzGhyz** [comment]
Hey @casoetan, great to see you're interested!

We're cautious of supporting additional frameworks as we're heavily maintaining them afterwards, lots of moving pieces to take care of. Regardless, it's our ambition to have Forest sit on anyone's stack so, the more people express their need for HapiJS support the faster we'll bring it :)

Regarding a guide for extending our current connector's base there is one here: [doc.forestadmin.com/api-reference](doc.forestadmin.com/api-reference/). You can also have a look at all our repos, everything connector-wise is open sourced. If you decide to do this, we'll be happy to help you throughout the process.

Hope that makes sense, let me know otherwise!
