### ISSUE TITLE
The .forestadmin-schema.json file does not exists. The schema cannot be synchronized with Forest Admin servers.

### ISSUE THREAD

**Issue by barracuda75** [ForestAdmin/forest-express-sequelize#260]
Hello there,
I need your help ...
I am using sequelize 5.7.0 and forest-express-admin, i tried everything on the documentation but it doesn't work at all.
Normally if you run `npm start` with documentation's settings it should create .json file from schema but ...
I get this error all the time `The .forestadmin-schema.json file does not exists.` please HELP !!

**Comment by arnaudbesnier** [comment]
Hi @barracuda75, what is the value of your `NODE_ENV` environment variable in the environment you are trying to setup the liana?

**Comment by barracuda75** [comment]
Hier @arnaudbesnier, i set NODE_ENV on "locale"

**Comment by arnaudbesnier** [comment]
Ok I think that is the reason of your issue. The `.forestadmin-schema.json` file is generated if the `NODE_ENV` value is `development` or `dev` if I remember well.

Could you change it and try again?

**Comment by barracuda75** [comment]
I tried your suggestion and it works only to create JSON but if i want to use my own environment  like 'local'. And why 'forest cannot reach data' ?

**Comment by arnaudbesnier** [comment]
Hi @barracuda75 

Reading this thread:
https://stackoverflow.com/questions/16978256/what-is-node-env-in-express
I am wondering if `local` or `locale` is very conventional.
`development` and `production` are the "valid" options in my opinion (see the thread)

Is there a reason why you use `local` instead of `development`?


Not sure to understand the "why 'forest cannot reach data' ?"...
If you need help on this point please take the time to provide much more context.
But I think this is another issue.
For a live support feel free to join: http://community.forestadmin.com/
